name: Send Email via Local SMTP (Port 465)

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install msmtp

      - name: Configure msmtp (using SSL and port 465)
        run: |
          # Create msmtp configuration file
          echo "defaults" > ~/.msmtprc
          echo "tls on" >> ~/.msmtprc  # Enable TLS
          echo "tls_certcheck off" >> ~/.msmtprc  # Disable certificate checking for simplicity
          echo "auth off" >> ~/.msmtprc  # Assuming no authentication (configure as needed)
          echo "host 127.0.0.1" >> ~/.msmtprc  # Local SMTP server
          echo "port 465" >> ~/.msmtprc  # Use port 465 for SSL
          echo "from sender@example.com" >> ~/.msmtprc  # Replace with actual sender email
          echo "to phanthomtables@gmail.com" >> ~/.msmtprc  # Replace with actual recipient email
          chmod 600 ~/.msmtprc  # Secure the config file

      - name: Test msmtp configuration
        run: |
          cat ~/.msmtprc  # Print the configuration file for debugging
          echo "Subject: Test Email from GitHub Actions (Port 465)" | msmtp -v phanthomtables@gmail.com
          echo "This email was sent via SSL on port 465 using msmtp." | msmtp phanthomtables@gmail.com
